// SPDX-License-Identifier: AGPL-3.0-or-later
import { readFile } from "fs/promises";
import { getCatalog, getDomainPriority } from "./catalog.js";
import type { CatalogSkill } from "./catalog.js";

// ── Layer Types ──────────────────────────────────────

export type LayerName = 'core' | 'extended' | 'reference';

// ── Fetching & Formatting ────────────────────────────

export async function fetchSkillContent(source: string): Promise<string> {
  if (source.startsWith("http://") || source.startsWith("https://")) {
    const res = await fetch(source);
    if (!res.ok) throw new Error(`HTTP ${res.status} ${res.statusText}`);
    return res.text();
  }
  return readFile(source, "utf-8");
}

export function stripFrontmatter(content: string): string {
  return content.replace(/^---[\s\S]*?---\n*/, "").trim();
}

export function formatSection(skill: CatalogSkill, rawContent: string): string {
  const body = stripFrontmatter(rawContent);
  return [
    `## ${skill.name}`,
    `<!-- source: ${skill.repo} | domains: ${skill.domains.join(", ")} | id: ${skill.id} -->`,
    "",
    body,
  ].join("\n");
}

// ── Layer Assembly ───────────────────────────────────

export function assembleSuperSkill(opts: {
  layer: 'core' | 'extended' | 'reference';
  profileName: string;
  sections: string[];
  skillCount: number;
  domainCount: number;
  fetchErrors: string[];
}): string {
  const now = new Date().toISOString();
  const layerLabel: Record<string, string> = {
    core: "Core — always loaded",
    extended: "Extended — medium+ context models",
    reference: "Reference — large context models only",
  };
  const estimatedTokens = Math.ceil(opts.sections.join("").length / 4);

  const lines: string[] = [
    "---",
    "name: super-skill",
    `layer: ${opts.layer}`,
    `description: ${layerLabel[opts.layer]} — ${opts.skillCount} skills across ${opts.domainCount} domains`,
    `version: ${now.slice(0, 10)}`,
    `estimated_tokens: ${estimatedTokens}`,
    "---",
    "",
    `# Super Skill — ${opts.layer.charAt(0).toUpperCase() + opts.layer.slice(1)}`,
    "",
    `> Generated by **superskill** skill marketplace`,
    `> Profile: **${opts.profileName}** | Layer: **${opts.layer}** | Skills: **${opts.skillCount}** | Domains: **${opts.domainCount}** | Generated: ${now}`,
    "",
  ];

  if (opts.fetchErrors.length > 0) {
    lines.push("## Fetch Errors", "");
    for (const err of opts.fetchErrors) {
      lines.push(`- ${err}`);
    }
    lines.push("");
  }

  if (opts.sections.length > 0) {
    lines.push(opts.sections.join("\n\n---\n\n"));
    lines.push("");
  }

  return lines.join("\n");
}

// ── Layer Classifier ─────────────────────────────────

export function classifySkill(skillId: string, collisionWinnerIds: Set<string>): LayerName {
  // Collision winners always go to core
  if (collisionWinnerIds.has(skillId)) return 'core';

  const entry = getCatalog().find((s) => s.id === skillId);
  if (!entry) return 'reference';

  // Use highest-priority domain
  let best: LayerName = 'reference';
  for (const domain of entry.domains) {
    const priority = getDomainPriority(domain);
    if (priority === 'core') return 'core';
    if (priority === 'extended') best = 'extended';
  }
  return best;
}
